# Generated by Django 4.0.5 on 2022-12-16 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='recipeMade',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
