# Generated by Django 4.0.5 on 2022-12-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_listing_recipemade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='recipeMade',
            field=models.CharField(max_length=5000),
        ),
    ]
