# Generated by Django 4.0.5 on 2022-12-16 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_listing_recipemade'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ingredients',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
