# Generated by Django 4.0.5 on 2022-12-17 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='post_like',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
