# Generated by Django 4.0.5 on 2022-12-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_listing_post_like_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
