# Generated by Django 4.0.5 on 2022-12-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_item_shoppingcart_shoppingcartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='shopping_cart',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
