# Generated by Django 4.0.5 on 2022-12-22 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_shoppingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
